export const API_BASE_URL = "https://m1.dysnomia.studio"
export const API_TOP_10_GAMES_URL = "/api/Games/top"

export const API_USER_REGISTER = "/api/Users/register"
export const API_USER_LOGIN = "/api/Users/auth"
export const API_USER_RENEW_TOKEN = "/api/Users/renewToken"
export const API_USER_DELETE = "/api/Users"
export const API_USER_INFO = "/api/Users/me"
export const API_GAME_DETAIL = "/api/Games"
export const API_COVER_URL = "/api/Games/covers"
export const API_SCREENSHOTS_URL = "/api/Games/screenshots"
export const API_SEARCH_URL = "/api/Games/search"
export const API_COMPANIES_URL = "/api/Companies"
